main: torben.rankplugin.Main
version: 1.0
name: RankPlugin
api-version: 1.13
author: Torben

commands:
  rank:
    description: The main command for the rank plugin
  template:
    description: Main command for TemplatePlugin. Use /template help for more info
permissions:
  template.user:
    description: Allows player to use the plugin's user features
    default: true
  template.admin:
    description: Allows player to use the plugin's admin features
    default: op